apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: emp-mgmt-frontend
