apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-app
  name: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - image: shubhamb756/employee-management:2.0
        name: mysql-app
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-7-99
